# shop1.yaml

name: "Ark"

# The main sitemap locations: products 1 to 13
sitemap_urls: ["https://www.ark.no/api/sitemap/products/1.xml",
                "https://www.ark.no/api/sitemap/products/2.xml",
                "https://www.ark.no/api/sitemap/products/3.xml",
                "https://www.ark.no/api/sitemap/products/4.xml",
                "https://www.ark.no/api/sitemap/products/5.xml",
                "https://www.ark.no/api/sitemap/products/6.xml",
                "https://www.ark.no/api/sitemap/products/7.xml",
                "https://www.ark.no/api/sitemap/products/8.xml",
                "https://www.ark.no/api/sitemap/products/9.xml",
                "https://www.ark.no/api/sitemap/products/10.xml",
                "https://www.ark.no/api/sitemap/products/11.xml",
                "https://www.ark.no/api/sitemap/products/12.xml",
                "https://www.ark.no/api/sitemap/products/13.xml"]

# Optional: If you have more sitemaps (some sites have multiple sitemaps)
# sitemap_urls:
#   - "https://www.shop1.com/sitemap1.xml"
#   - "https://www.shop1.com/sitemap2.xml"

# You can also include filtering rules to skip certain URLs
# For example, ignoring category pages or blog pages:
ignore_patterns:
  - "/blog/"
  - "/category/"
  - "web_widget/"

# Selectors to parse each product detail page
selectors:
  product_name:
    selector: "h1.font-display.font-semibold::text"
    join_text: false  # or omit if you want

  description:
    selector: '#innhold > div.bg-neutral-20.w-full > article > div > div > div.bg-white.lg\:grid.lg\:grid-cols-2.lg\:items-center.px-4.pt-6.md\:px-6.rounded-t-2xl.lg\:grid-rows-\[auto_auto_auto_auto_1fr\] > div.lg\:px-6.xl\:px-10.pb-4.lg\:pb-6 > div::text'
    join_text: true

  price: 
    selector: "div.font-semibold.text-\\[2\\.375rem\\].leading-none::text"
    join_text: false
  brand: "#acc-product-details dl dd.font-display.font-semibold::text"

extras:
  format:
    selector: "//dt[normalize-space()='Format']/following-sibling::dd[1]/text()"
    join_text: false
  published_year:
    selector: "//dt[normalize-space()='Utgivelsesår']/following-sibling::dd[1]/text()"
    join_text: false
  publisher:
    selector: "//dt[normalize-space()='Forlag']/following-sibling::dd[1]/text()"
    join_text: false
  language:
    selector: "//dt[normalize-space()='Språk']/following-sibling::dd[1]/text()"
    join_text: false
  number_of_pages:
    selector: "//dt[normalize-space()='Antall sider']/following-sibling::dd[1]/text()"
    join_text: false
  height:
    selector: "//dt[normalize-space()='Høyde']/following-sibling::dd[1]/text()"
    join_text: false
  width:
    selector: "//dt[normalize-space()='Bredde']/following-sibling::dd[1]/text()"
    join_text: false
  length:
    selector: "//dt[normalize-space()='Lengde']/following-sibling::dd[1]/text()"
    join_text: false
  weight:
    selector: "//dt[normalize-space()='Vekt']/following-sibling::dd[1]/text()"
    join_text: false
  series:
    selector: "//dt[normalize-space()='Serie']/following-sibling::dd[1]/text()"
    join_text: false
  isbn:
    selector: "//dt[normalize-space()='ISBN']/following-sibling::dd[1]/text()"
    join_text: false
  author:
    selector: '//*[@id="innhold"]/div[1]/article/div/div/div[1]/header/div/div/div/span/a'


